#!/bin/bash -e

# 'tools/build/v2' is located at 'tools/build' now!
if [ ${PWD##*/} = 'boost-fixup' ]
then
  git filter-branch --tree-filter "find . -type f -maxdepth 1 -exec sed -i -e 's|build[/\\]v2|build|g' {} \;"
fi

# don't bother with these two
if [ ${PWD##*/} = 'sandbox' ] || [ ${PWD##*/} = 'boost-fixup' ]
then
  exit 0
fi

# remove merged branches
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d

# remove empty branches
for branch in $(git branch | cut -c 3-)
do
  if [ $(git ls-tree $branch | wc -m) -eq 0 ]
  then
    git branch -D $branch
  fi
done

# cleanup garbage, if required
git gc --auto --quiet

# allow pushing bigger files
git config http.postBuffer 524288000
