#!/bin/bash -xe

# don't bother with these two
if [ ${PWD##*/} = 'sandbox' ] || [ ${PWD##*/} = 'boost-fixup' ]
then
  exit 0
fi

# remove redundant parents in merge commits; remove commits with a single parent and that makes no change to the tree
git filter-branch --force --parent-filter 'read commit; test -z "$commit" || git show-branch --independent `echo -n "$commit" | sed -e "s/-p / /g"` | sed -e "s/.*/-p &/" | tr "\n" " "; echo' --commit-filter='git_commit_non_empty_tree "$@"' -- --all 1>/dev/null 2>&1

# remove merged branches
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d

# remove empty branches
for branch in $(git branch | cut -c 3-)
do
  if [ $(git ls-tree $branch | wc -m) -eq 0 ]
  then
    git branch -D $branch
  fi
done

# cleanup garbage, if required
git gc --auto --quiet

# allow pushing bigger files
git config http.postBuffer 524288000
