#!/bin/bash

# remove merged branches
git branch --merged | grep -v "\*" | xargs -n 1 git branch -d

# remove redundant parents in merge commits
git filter-branch --force --parent-filter 'read commit; test -z "$commit" || git show-branch --independent `echo -n "$commit" | sed -e "s/-p / /g"` | sed -e "s/.*/-p &/" | tr "\n" " "; echo' -- --all 1>/dev/null 2>&1

#TODO:
# remove empty commits that don't have a parent?
